before_install:
- openssl aes-256-cbc -K $encrypted_4fd1003c0e5b_key -iv $encrypted_4fd1003c0e5b_iv
  -in deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
- chmod 400 ~/.ssh/deploy_rsa
- chmod +x push.sh

jobs:
  include:
  - stage: Push
    script: 
      - ./push.sh